[project]
name = "robot-guide"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "asyncio>=4.0.0",
    "gradio>=6.26.0",
    "loguru>=0.7.3",
    "miniaudio>=1.61",
    "numpy>=2.2.6",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "sounddevice>=0.5.3",
]
