"""Cross-platform MP3 and raw PCM playback helpers."""

import time
from pathlib import Path


BASE_DIR = Path(__file__).resolve().parent.parent
OUTPUT_DIR = BASE_DIR / "output"


class PCMStream:
    """Persistent low-latency stream for signed 16-bit PCM audio."""

    def __init__(self, sample_rate: int = 16000, channels: int = 1) -> None:
        import sounddevice as sd

        self.stream = sd.RawOutputStream(
            samplerate=sample_rate,
            channels=channels,
            dtype="int16",
            latency="low",
        )

    def __enter__(self) -> "PCMStream":
        self.stream.start()
        return self

    def write(self, pcm: bytes) -> None:
        """Play one raw PCM chunk."""

        self.stream.write(pcm)

    def play_file(self, audio_file: str | Path) -> None:
        """Play a raw PCM file through the open stream."""

        path = Path(audio_file)
        with path.open("rb") as file:
            while chunk := file.read(4096):
                self.write(chunk)

    def __exit__(self, *_: object) -> None:
        self.stream.stop()
        self.stream.close()


class AudioPlayer:
    """Play MP3 or signed 16-bit raw PCM audio files."""

    def play(
        self,
        audio_file: str | Path,
        *,
        sample_rate: int = 16000,
        channels: int = 1,
    ) -> None:
        path = Path(audio_file)
        if path.suffix.lower() == ".mp3":
            self.play_mp3(path)
        elif path.suffix.lower() == ".pcm":
            self.play_pcm(path, sample_rate=sample_rate, channels=channels)
        else:
            raise ValueError(f"Unsupported audio file: {path}")

    @staticmethod
    def play_mp3(audio_file: str | Path) -> None:
        """Decode and play an MP3 file with miniaudio."""

        import miniaudio

        path = Path(audio_file)
        stream = miniaudio.stream_file(str(path))
        with miniaudio.PlaybackDevice(buffersize_msec=100) as device:
            device.start(stream)
            while device.callback_generator is not None:
                time.sleep(0.01)
            time.sleep(device.buffersize_msec / 1000)

    @staticmethod
    def play_pcm(
        audio_file: str | Path,
        *,
        sample_rate: int = 16000,
        channels: int = 1,
    ) -> None:
        """Play a signed 16-bit raw PCM file."""

        with PCMStream(sample_rate, channels) as stream:
            stream.play_file(audio_file)


def demo_mp3() -> None:
    """Play the demo MP3 file."""

    AudioPlayer().play_mp3(OUTPUT_DIR / "byteplus_demo.mp3")


def demo_pcm() -> None:
    """Play the 16 kHz mono PCM file generated by BytePlusTTS."""

    AudioPlayer().play_pcm(OUTPUT_DIR / "byteplus_demo.pcm")


def main() -> None:
    demo_mp3()
    demo_pcm()


if __name__ == "__main__":
    main()
